# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: 34.230.71.163
  become: yes

  tasks:

- name: Call Roles
  hosts: 34.230.71.163
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd